project_id = "lguzfxcefsnmwrfjhzfb"

[functions.check-unpaid-deliveries]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = true

[functions.initiate-mpesa-payment]
verify_jwt = false

[functions.mpesa-webhook]
verify_jwt = false

[functions.send-delivery-confirmation]
verify_jwt = true

[functions.submit-delivery-query]
verify_jwt = false